export { default as Actors } from "./Actors"
export { default as MovieInformation } from "./MovieInformation"
export { default as Movies } from "./Movies"
export { default as Profile } from "./Profile"
export { default as Sidebar } from "./Sidebar"
export { default as Navbar } from "./Navbar"
export { default as Movie } from "./Movie"